sudo: false
warnings_are_errors: false

language: node_js
node_js: "10.18.0"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: Deploy Mac
      os: osx
      script:
        - npm run make-mac-installer
    - stage: Deploy Linux
      os: linux
      script:
        - npm run make-linux-installer